FROM debian:stable-slim AS build
ARG VERSION
ARG BUILD_TYPE

WORKDIR /src
COPY ./scripts ./scripts
RUN ./scripts/build.sh ${BUILD_TYPE} ${VERSION}

FROM debian:stable-slim

RUN apt-get update && apt-get install -y \
    libpcre3 libpcre3-dev \
    libssl3 libssl-dev

COPY --from=build /usr/local/nginx /usr/local/nginx

ENV PATH="/usr/local/nginx/sbin:$PATH"

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
