FROM debian:stable-slim AS build
ARG VERSION
ARG BUILD_TYPE

WORKDIR /src
COPY ./scripts ./scripts
RUN ./scripts/build.sh ${BUILD_TYPE} ${VERSION}

FROM debian:stable-slim

COPY --from=build /usr/local/nginx /usr/local/nginx
COPY --from=build /src/scripts/deps.sh .

RUN ./deps.sh ${BUILD_TYPE} && rm ./deps.sh

ENV PATH="/usr/local/nginx/sbin:$PATH"

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
